version: "3.9"
   
services:
  web:
    build: .
    image: notificationhubpoc:latest
    environment:
      - AzureNotificationHub__ConnectionString=${HubName}
      - AzureNotificationHub__HubName=${HubConStr}

    ports:
      - "8080:80"
      - "8043:443"
